export const properties = [
  {
    id: 'harlow',
    tag: 'Available',
    price: '$8,400,000',
    name: 'The Harlow Residence',
    location: 'Bel Air, Los Angeles',
    beds: 6, baths: 7, sqft: '9,200',
    gradient: 'linear-gradient(135deg, #2D3B2A 0%, #4A6B40 100%)',
    desc: 'A masterwork of California modernism set on 1.2 acres in the heart of Bel Air. Floor-to-ceiling glass, motorized overhangs, and a seamless indoor-outdoor flow that captures the spirit of the hills.',
    year: 2022,
  },
  {
    id: 'meridian',
    tag: 'Under Offer',
    price: '$14,200,000',
    name: 'One Meridian Tower',
    location: 'Tribeca, New York',
    beds: 5, baths: 5, sqft: '7,800',
    gradient: 'linear-gradient(135deg, #1A2C3B 0%, #2A4A5A 100%)',
    desc: 'A full-floor residence commanding unobstructed skyline views from one of Tribeca\'s most prestigious new addresses. Cerused oak, Calacatta stone, and bespoke millwork throughout.',
    year: 2023,
  },
  {
    id: 'constanza',
    tag: 'Available',
    price: '$5,900,000',
    name: 'Villa Constanza',
    location: 'Miami Beach, FL',
    beds: 4, baths: 4, sqft: '5,400',
    gradient: 'linear-gradient(135deg, #3B2A1A 0%, #6B4A2A 100%)',
    desc: 'Tucked behind a walled garden on a premier Miami Beach street, this tropical modernist villa is a serene counterpoint to the city\'s energy — with a 60ft lap pool and rooftop terrace.',
    year: 2021,
  },
  {
    id: 'kensington',
    tag: 'Available',
    price: '$22,500,000',
    name: 'Kensington Manor',
    location: 'Kensington, London',
    beds: 8, baths: 9, sqft: '12,000',
    gradient: 'linear-gradient(135deg, #2A1A2C 0%, #4A2A5A 100%)',
    desc: 'A Grade II-listed townhouse on one of Kensington\'s finest garden squares, extensively restored with contemporary interiors by a renowned London studio. Cinema, gym, wine room, and staff quarters.',
    year: 2019,
  },
  {
    id: 'aspen',
    tag: 'Available',
    price: '$3,750,000',
    name: 'Aspen Ridge Lodge',
    location: 'Aspen, Colorado',
    beds: 5, baths: 6, sqft: '6,100',
    gradient: 'linear-gradient(135deg, #1E2A3B 0%, #2A3A4A 100%)',
    desc: 'A mountain contemporary nestled into the hillside with direct ski-in access, dramatic steel-and-glass architecture, and panoramic views of the Elk Mountain range.',
    year: 2020,
  },
]

export type Property = typeof properties[0]
